source "https://rubygems.org"

gem "thor", "~> 0.19"
gem "pg", "~> 0.18"
gem "activesupport", "~> 4.0.13"
gem "pry", "~> 0.10.3"
gem "rack", "~> 2.0"

gem "bundler", "~> 1.11"
gem "rake", "~> 10.0"
gem "rspec", "~> 3.0"
